apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: consul-pod-list-binding
  namespace: consul
subjects:
- kind: ServiceAccount
  name: consul-agent
roleRef:
  kind: Role
  name: consul-pod-list
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: consul-pod-list-default-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: consul-agent
  namespace: consul
roleRef:
  kind: Role
  name: consul-pod-list-default
  apiGroup: rbac.authorization.k8s.io
