apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: consul-pod-list
  namespace: consul
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: consul-pod-list-default
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
