apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
name: bm-cluster
versions:
  kubernetes: '1.25.6'
cloudProvider:
  none: {}

features:
  nodeLocalDNS:
    deploy: false

controlPlane:
  hosts:
#    - privateAddress: '10.1.1.61'
#      sshUsername: riff
    - privateAddress: '10.1.1.62'
      sshUsername: riff
    - privateAddress: '10.1.1.63'
      sshUsername: riff

staticWorkers:
  hosts:
#    - privateAddress: '10.1.1.154'
#      sshUsername: riff
#    - privateAddress: '10.1.1.155'
#      sshUsername: riff
#    - privateAddress: '10.1.1.156'
#      sshUsername: riff

# Provide the external address of your load balancer or the public addresses of
# the first control plane nodes.
apiEndpoint:
  host: '10.1.1.101'
  port: 6444

machineController:
  deploy: false
