apiVersion: "tinkerbell.org/v1alpha1"
kind: Hardware
metadata:
  name: auth03
  namespace: tink-system
spec:
  disks:
    - device: /dev/sda
  metadata:
    facility:
      facility_code: onprem
    manufacturer:
      slug: proxmox
    instance:
      userdata: ""
      hostname: "auth03"
      id: "06:98:fc:6a:44:03"
      operating_system:
        distro: "debian"
        os_slug: "debian_12"
        version: "12"
  interfaces:
    - dhcp:
        arch: x86_64
        hostname: auth03
        ip:
          address: 10.1.1.63
          gateway: 10.1.1.1
          netmask: 255.255.0.0
        lease_time: 86400
        mac: 06:98:fc:6a:44:03
        name_servers:
          - 10.1.1.53
        uefi: true
      netboot:
        allowPXE: true
        allowWorkflow: true
