apiVersion: "tinkerbell.org/v1alpha1"
kind: Hardware
metadata:
  name: auth02
  namespace: tink-system
spec:
  disks:
    - device: /dev/sda
  metadata:
    facility:
      facility_code: onprem
    manufacturer:
      slug: proxmox
    instance:
      userdata: ""
      hostname: "auth02"
      id: "8a:2d:e0:7c:2b:1c"
      operating_system:
        distro: "debian"
        os_slug: "debian_12"
        version: "12"
  interfaces:
    - dhcp:
        arch: x86_64
        hostname: auth02
        ip:
          address: 10.1.1.62
          gateway: 10.1.1.1
          netmask: 255.255.0.0
        lease_time: 86400
        mac: 8a:2d:e0:7c:2b:1c
        name_servers:
          - 10.1.1.53
        uefi: true
      netboot:
        allowPXE: true
        allowWorkflow: true
