apiVersion: "tinkerbell.org/v1alpha1"
kind: Hardware
metadata:
  name: haproxy01
  namespace: tink-system
spec:
  disks:
    - device: /dev/sda
  metadata:
    facility:
      facility_code: onprem
    manufacturer:
      slug: proxmox
    instance:
      userdata: ""
      hostname: "haproxy01"
      id: "2e:b8:52:0b:70:86"
      operating_system:
        distro: "debian"
        os_slug: "debian_12"
        version: "12"
  interfaces:
    - dhcp:
        arch: x86_64
        hostname: haproxy01
        ip:
          address: 10.1.1.11
          gateway: 10.1.1.1
          netmask: 255.255.0.0
        lease_time: 86400
        mac: 2e:b8:52:0b:70:86
        name_servers:
          - 10.1.1.53
        uefi: true
      netboot:
        allowPXE: true
        allowWorkflow: true
