apiVersion: "tinkerbell.org/v1alpha1"
kind: Workflow
metadata:
  name: wf-auth01
  namespace: tink-system
spec:
  templateRef: debian12
  hardwareRef: auth01
  hardwareMap:
    device_1: 2e:cb:78:c4:96:eb
