apiVersion: v1
items:
- apiVersion: tinkerbell.org/v1alpha1
  kind: Template
  metadata:
    annotations:
      meta.helm.sh/release-name: tink-flow-release
      meta.helm.sh/release-namespace: tink-system
    creationTimestamp: "2023-10-10T00:38:36Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
    name: debian12
    namespace: tink-system
    resourceVersion: "5686"
    uid: 23a5f96e-e11d-4ebc-934d-aa2987abaf17
  spec:
    data: |
      version: "0.1"
      name: debian12
      global_timeout: 1800
      tasks:
        - name: "os-installation"
          worker: ""
          volumes:
            - /dev:/dev
            - /dev/console:/dev/console
            - /lib/firmware:/lib/firmware:ro
          actions:
            - name: "stream-debian-image"
              image: quay.io/tinkerbell-actions/image2disk:v1.0.0
              timeout: 600
              environment:
                DEST_DISK: /dev/sda
                # Hegel IP
                IMG_URL: "http://10.1.1.151:80/images/debian-12-amd64.raw.gz"
                COMPRESSED: true
            - name: "grow-partition"
              image: quay.io/tinkerbell-actions/cexec:v1.0.0
              timeout: 90
              environment:
                BLOCK_DEVICE: /dev/sda1
                FS_TYPE: ext4
                CHROOT: y
                CMD_LINE: "growpart /dev/sda 1"
            - name: "resize2fs"
              image: quay.io/tinkerbell-actions/cexec:v1.0.0
              timeout: 90
              environment:
                BLOCK_DEVICE: /dev/sda1
                FS_TYPE: ext4
                CHROOT: y
                CMD_LINE: "resize2fs /dev/sda1"
            - name: "add-tink-cloud-init-config"
              image: quay.io/tinkerbell-actions/writefile:v1.0.0
              timeout: 90
              environment:
                DEST_DISK: /dev/sda1
                FS_TYPE: ext4
                DEST_PATH: /etc/cloud/cloud.cfg.d/10_tinkerbell.cfg
                UID: 0
                GID: 0
                MODE: 0600
                DIRMODE: 0700
                CONTENTS: |
                  datasource_list: [Ec2]
                  datasource:
                    Ec2:
                      # Hegel IP
                      metadata_urls: ["http://10.1.1.24:50061"]
                      strict_id: false
                      apply_full_imds_network_config: false
                      max_wait: 30
                      timeout: 10
                  system_info:
                    default_user:
                      name: riff
                      groups: [wheel, adm, sudo]
                      sudo: ["ALL=(ALL) NOPASSWD:ALL"]
                      shell: /bin/bash
                  package_upgrade: true
                  packages:
                    - htop
                    - git
                    - qemu-guest-agent
                  users:
                  - name: riff
                    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
                    shell: /bin/bash
                    ssh_authorized_keys:
                      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAXcIkcYMXYY4CFHJv7O6946HDJrh+w4IqFExRSTt7oN wings@trevor"
                      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP6vPhGaO6fVdmS6IhAb+A+MXlkAsBN2BeIVJQaD7Vqf wings@chase"
                      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO584u1bj3QIb2kHH5651233CKFwOqlG6fDD6T0YanjU pcadmin@stellar"
                  warnings:
                    dsid_missing_source: off
                  runcmd:
                    - [ systemctl, start, qemu-guest-agent ]
            - name: "add-tink-cloud-init-ds-config"
              image: quay.io/tinkerbell-actions/writefile:v1.0.0
              timeout: 90
              environment:
                DEST_DISK: /dev/sda1
                FS_TYPE: ext4
                DEST_PATH: /etc/cloud/ds-identify.cfg
                UID: 0
                GID: 0
                MODE: 0600
                DIRMODE: 0700
                CONTENTS: |
                  datasource: Ec2
            - name: "force-dhcp-mac-identifier"
              image: quay.io/tinkerbell-actions/cexec:v1.0.0
              timeout: 90
              environment:
                BLOCK_DEVICE: /dev/sda1
                FS_TYPE: ext4
                CHROOT: y
                DEFAULT_INTERPRETER: "/bin/sh -c"
                CMD_LINE: >
                  awk 'BEGIN { found=0 } (!/^#/) && /^send dhcp-client-identifier/ { print "send dhcp-client-identifier \"\""; found=1; next } 1; END { if (found==0) print "send dhcp-client-identifier \"\"" }' /etc/dhcp/dhclient.conf > /etc/dhcp/dhclient.conf.new && mv /etc/dhcp/dhclient.conf.new /etc/dhcp/dhclient.conf
            - name: "reboot"
              image: public.ecr.aws/l0g8r8j6/tinkerbell/hub/reboot-action:latest
              timeout: 90
              volumes:
              - /worker:/worker
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
