apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: ldap
    app.kubernetes.io/managed-by: manual
    app.kubernetes.io/name: authentik-ldap-loadbalancer
    app.kubernetes.io/version: 2023.8.3
    goauthentik.io/outpost-name: ldap
    goauthentik.io/outpost-type: ldap
  name: authentik-ldap-loadbalancer
  namespace: authentik
spec:
  ports:
  - name: ldap
    port: 389
    protocol: TCP
    targetPort: 3389
  - name: ldaps
    port: 636
    protocol: TCP
    targetPort: 6636
  selector:
    app.kubernetes.io/managed-by: goauthentik.io
    app.kubernetes.io/name: authentik-outpost-ldap
    goauthentik.io/outpost-name: ldap
    goauthentik.io/outpost-type: ldap
  type: LoadBalancer
  loadBalancerIP: 10.1.1.111
