apiVersion: "tinkerbell.org/v1alpha1"
kind: Workflow
metadata:
  name: wf-ipfs02
  namespace: tink-system
spec:
  templateRef: debian12
  hardwareRef: ipfs02
  hardwareMap:
    device_1: 26:24:da:4d:d8:27