---
- name: Apply basic configuration
  hosts: all
  become: true

  roles:
    - dns
    - root-user
    - { role: riff-user, when: not ldap_managed | default('false') }
    - geerlingguy.ntp
    - sshd
    # - sssd-ldap
    # - moosefs-mount
    # - sshd
    # - sudo
    # - utils
    # - network-tuning
    # - netbox-agent
    # - checkmk-agent