---
- name: Apply basic configuration
  hosts: all
  become: true

  roles:
    - dns
    # - ntp
    # - sssd-ldap
    # - moosefs-mount
    # - root-user
    # - riff-user
    # - sshd
    # - sudo
    # - utils
    # - network-tuning
    # - netbox-agent
    # - checkmk-agent