apiVersion: "tinkerbell.org/v1alpha1"
kind: Hardware
metadata:
  name: acme-dns01
  namespace: tink-system
spec:
  disks:
    - device: /dev/sda
  metadata:
    facility:
      facility_code: onprem
    manufacturer:
      slug: proxmox
    instance:
      userdata: ""
      hostname: "acme-dns01"
      id: "4e:90:67:0b:19:cd"
      operating_system:
        distro: "debian"
        os_slug: "debian_12"
        version: "12"
  interfaces:
    - dhcp:
        arch: x86_64
        hostname: acme-dns01
        ip:
          address: 10.1.1.56
          gateway: 10.1.1.1
          netmask: 255.255.0.0
        lease_time: 86400
        mac: 4e:90:67:0b:19:cd
        name_servers:
          - 10.1.1.53
        uefi: true
      netboot:
        allowPXE: true
        allowWorkflow: true
