operator:
  verify:
    enabled: false
ingress:
  main:
    addTraefikAnnotations: false
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "acme-prod"
    hosts:
      - host: requests.riff.cc
        paths:
        - path: /
          pathType: Prefix
    tls:
    - secretName: requests-tls-secret
      hosts:
      - "*.riff.cc"